services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mytrail-backend
    environment:
      MONGO_URI: mongodb://mongodb:27017
      PYTHONUNBUFFERED: "1"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mytrail-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
